//CREATE POSTS
export const CREATE_POST_REQUEST = "CREATE_POST_REQUEST";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_FAIL = "CREATE_POST_FAIL";

export const GET_POSTS_REQUEST = "GET_POSTS_REQUEST";
export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS";
export const GET_POSTS_FAIL = "GET_POSTS_FAIL";

export const CLEAR_POST_SUCCESS_AND_ERROR = "CLEAR_POST_SUCCESS_AND_ERROR";

export const GET_FEED_POSTS_REQUEST = "GET_FEED_POSTS_REQUEST";
export const GET_FEED_POSTS_SUCCESS = "GET_FEED_POSTS_SUCCESS";
export const GET_FEED_POSTS_FAIL = "GET_FEED_POSTS_FAIL";
