//CREATE POSTS
export const CREATE_POST_REQUEST = "CREATE_POST_REQUEST";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_FAIL = "CREATE_POST_FAIL";

export const GET_POSTS_REQUEST = "GET_POSTS_REQUEST";
export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS";
export const GET_POSTS_FAIL = "GET_POSTS_FAIL";

export const CLEAR_POST_SUCCESS_AND_ERROR = "CLEAR_POST_SUCCESS_AND_ERROR";

export const GET_FEED_POSTS_REQUEST = "GET_FEED_POSTS_REQUEST";
export const GET_FEED_POSTS_SUCCESS = "GET_FEED_POSTS_SUCCESS";
export const GET_FEED_POSTS_FAIL = "GET_FEED_POSTS_FAIL";

export const ADD_COMMENT_REQUEST = "ADD_COMMENT_REQUEST";
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS";
export const ADD_COMMENT_FAIL = "ADD_COMMENT_FAIL";

export const SINGLE_POST_REQUEST = "SINGLE_POST_REQUEST";
export const SINGLE_POST_SUCCESS = "SINGLE_POST_SUCCESS";
export const SINGLE_POST_FAIL = "SINGLE_POST_FAIL";

export const SP_COMMENT_GET_REQUEST = "SP_COMMENT_GET_REQUEST";
export const SP_COMMENT_GET_SUCCESS = "SP_COMMENT_GET_SUCCESS";
export const SP_COMMENT_GET_FAIL = "SP_COMMENT_GET_FAIL";

export const SP_COMMENT_ADD_REQUEST = "SP_COMMENT_ADD_REQUEST";
export const SP_COMMENT_ADD_SUCCESS = "SP_COMMENT_ADD_SUCCESS";
export const SP_COMMENT_ADD_FAIL = "SP_COMMENT_ADD_FAIL";

export const SINGLE_FEED_COMMENT_ADD_REQUEST =
  "SINGLE_FEED_COMMENT_ADD_REQUEST";
export const SINGLE_FEED_COMMENT_ADD_SUCCESS =
  "SINGLE_FEED_COMMENT_ADD_SUCCESS";
export const SINGLE_FEED_COMMENT_ADD_FAIL = "SINGLE_FEED_COMMENT_ADD_FAIL";

export const SINGLE_FEED_COMMENT_GET_REQUEST =
  "SINGLE_FEED_COMMENT_GET_REQUEST";
export const SINGLE_FEED_COMMENT_GET_SUCCESS =
  "SINGLE_FEED_COMMENT_GET_SUCCESS";
export const SINGLE_FEED_COMMENT_GET_FAIL = "SINGLE_FEED_COMMENT_GET_FAIL";
