export const CLEAR_ERRORS = "ALL_PRODUCT_CLEAR";

//LOGIN
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_REQUEST = "LOGIN_REQUEST";

// REGISTER USER
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";

//LOAD USER FROM COOKIES
export const LOAD_USER_FAIL = "LOAD_USER_FAIL";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST";

//LOGOUT
export const LOGOUT_FAIL = "LOGOUT_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

//UPDATE USER
export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";

export const SUGGESTION_USER_REQUEST = "SUGGESTION_USER_REQUEST";
export const SUGGESTION_USER_SUCCESS = "SUGGESTION_USER_SUCCESS";
export const SUGGESTION_USER_FAIL = "SUGGESTION_USER_FAIL";

//FOLL0WING USERS
export const FOLLOWING_USER_REQUEST = "FOLLOWING_USER_REQUEST";
export const FOLLOWING_USER_SUCCESS = "FOLLOWING_USER_SUCCESS";
export const FOLLOWING_USER_FAIL = "FOLLOWING_USER_FAIL";
//UNFOLL0WING USERS
export const UNFOLLOW_USER_REQUEST = "UNFOLLOW_USER_REQUEST";
export const UNFOLLOW_USER_SUCCESS = "UNFOLLOW_USER_SUCCESS";
export const UNFOLLOW_USER_FAIL = "UNFOLLOW_USER_FAIL";

//GET USER PROFILE
export const GET_USER_PROFILE_REQUEST = "GET_USER_PROFILE_REQUEST";
export const GET_USER_PROFILE_SUCCESS = "GET_USER_PROFILE_SUCCESS";
export const GET_USER_PROFILE_FAIL = "GET_USER_PROFILE_FAIL";
